const VALOR_AUXILIO_TRANSPORTE='valorAuxilioTransporte';
const VALOR_SALARIO_TRANSPORTE='valorSalarioTransporte';
const CONCEPTO_AUXILIO_TRANSPORTE='conceptoAuxilioTransporte';
const CONCEPTO_VACACION_SALARIO='conceptoVacacionesSalario';
const DESCRIPCION_CONCEPTO_AUXILIO_TRANSPORTE = 'Auxilio Transporte';
const CONCEPTO_LICENCIA_REMUNERADA='conceptoLicenciaRemunerada';
const CONCEPTO_LICENCIA_NOREMUNERADA='conceptoLicenciaNoRemunerada';
const CONCEPTO_INCAPACIDAD ='conceptoIncapacidad';
const GRUPO_IBC = 'grupoIBC';
 

module.exports = {
VALOR_AUXILIO_TRANSPORTE: VALOR_AUXILIO_TRANSPORTE,
VALOR_SALARIO_TRANSPORTE: VALOR_SALARIO_TRANSPORTE,
CONCEPTO_AUXILIO_TRANSPORTE :CONCEPTO_AUXILIO_TRANSPORTE,
CONCEPTO_VACACION_SALARIO:CONCEPTO_VACACION_SALARIO,
DESCRIPCION_CONCEPTO_AUXILIO_TRANSPORTE : DESCRIPCION_CONCEPTO_AUXILIO_TRANSPORTE,
CONCEPTO_LICENCIA_REMUNERADA :CONCEPTO_LICENCIA_REMUNERADA,
CONCEPTO_LICENCIA_NOREMUNERADA:CONCEPTO_LICENCIA_NOREMUNERADA,
CONCEPTO_INCAPACIDAD : CONCEPTO_INCAPACIDAD,
GRUPO_IBC : GRUPO_IBC


}

