const DIAS_COMERCIAL=30;
const DIAS_JULIANO =31;
const CODIGO_DIAS_JULIANO ='J';
const CODIGO_DIAS_COMERCIAL ='C';
const CODIGO_PENDIENTE ='P';
const TIPO_AJUSTE_SUMA ='S';
const TIPO_AJUSTE_RESTA ='R';


module.exports = {
    DIAS_JULIANO: DIAS_JULIANO,
    DIAS_COMERCIAL:DIAS_COMERCIAL,
    CODIGO_DIAS_COMERCIAL :CODIGO_DIAS_COMERCIAL,
    CODIGO_DIAS_JULIANO : CODIGO_DIAS_JULIANO,
    CODIGO_PENDIENTE : CODIGO_PENDIENTE,
    TIPO_AJUSTE_RESTA: TIPO_AJUSTE_RESTA,
    TIPO_AJUSTE_SUMA : TIPO_AJUSTE_SUMA
}

