const DIAS_COMERCIAL=30;
const DIAS_JULIANO =31;
const CODIGO_DIAS_JULIANO ='J';
const CODIGO_DIAS_COMERCIAL ='C';
const CODIGO_PENDIENTE ='P';
const CODIGO_APROBADO = 'A';
const CODIGO_RECHAZADO = 'R';
const NOVEDAD_PENDIENTE = 'P';
const NOVEDAD_APROBADA = 'A';
const TIPO_AJUSTE_SUMA ='S';
const TIPO_AJUSTE_RESTA ='R';
const ESTADO_PRESTAMO_PENDIENTE ='P';
const ESTADO_PRESTAMO_PAGADO = 'G';
const LISTA_TIPOS_INCAPACIDAD = 
[

{
   code: 'G',
   description:'General'
},
{
    code: 'A',
    description:'Accidente de Trabajo'
},
{
    code: 'M',
    description:'Maternidad'
},
{
    code: 'P',
    description:'Paternidad'
}

];



module.exports = {
    DIAS_JULIANO: DIAS_JULIANO,
    DIAS_COMERCIAL:DIAS_COMERCIAL,
    CODIGO_DIAS_COMERCIAL :CODIGO_DIAS_COMERCIAL,
    CODIGO_DIAS_JULIANO : CODIGO_DIAS_JULIANO,
    CODIGO_PENDIENTE : CODIGO_PENDIENTE,
    TIPO_AJUSTE_RESTA: TIPO_AJUSTE_RESTA,
    TIPO_AJUSTE_SUMA : TIPO_AJUSTE_SUMA,
    LISTA_TIPOS_INCAPACIDAD : LISTA_TIPOS_INCAPACIDAD,
    NOVEDAD_PENDIENTE :NOVEDAD_PENDIENTE,
    NOVEDAD_APROBADA :NOVEDAD_APROBADA,
    ESTADO_PRESTAMO_PENDIENTE :ESTADO_PRESTAMO_PENDIENTE,
    ESTADO_PRESTAMO_PAGADO : ESTADO_PRESTAMO_PAGADO,
    CODIGO_APROBADO : CODIGO_APROBADO,
    CODIGO_RECHAZADO:CODIGO_RECHAZADO
}

